### PR TITLE
Updates to verify [WIP]

### PR DESCRIPTION
**Pull request by mandeep**
Added recipe and package tests, added updates from anaconda-verify, fixed bugs found as a result of tests, and added a .travis.yml file for CI.

### CODE REVIEW

**Comment by mandeep** [comment]
@msarahan I tried a few things to fix the Py2 unicode errors, but ran into the same problem you're having with the UnicodeEncodeError. From what I read this is because the error code is mixing a unicode string and a text str. Do you want me to try to get things strings working properly? If nothing else, we could just change the error code to not print unicode chars.

**Comment by msarahan** [comment]
Thanks!  I'm going to keep tweaking it, but if you also want to work in parallel, go for it.  Come to think of it, if you work on this, I'll go tag the new conda-build stuff that was necessary, so maybe we can get an all-green build.

**Comment by mandeep** [comment]
Of course! I have a few ideas that I want to try with the unicode errors.

**Comment by mandeep** [comment]
These changes in commit https://github.com/conda/conda-verify/pull/11/commits/684acb7e7a877f79cbfeb3a2a42a5a7bb0750200 don't work as intended. Instead of comparing the fields in the meta.yaml, it's comparing the fields in the subfields. For example the failing recipe is comparing ``{'build': [], 'host': [], 'run': []}`` to ``{'preferred_env', 'host', 'preferred_env_executable_paths', 'run', 'build'}
``

```
            subfield = self.meta.get(section)
            if hasattr(subfield, 'keys'):
                import pdb; pdb.set_trace()
                for key in subfield:
                    if key not in FIELDS[section]:
                        return Error(self.recipe_dir, 'C2110', u'Found invalid field "{}" in section "{}"' .format(key, section))
            else:
                # list of dicts.  Used in source and outputs.
                for entry in subfield:
                    for key in entry:
                        if key not in FIELDS[section]:
                            return Error(self.recipe_dir, 'C2110', u'Found invalid field "{}" in section "{}"' .format(key, section))
```

**Comment by msarahan** [comment]
hmmm... I guess I misunderstood that test.  I thought I was adjusting it to compare subfields when those subfields were things like lists of dicts.  Can you recommend a better test here?

**Comment by mandeep** [comment]
The check was only to check if the subfield was listed in the specific key in the FIELDS dict in constants.py. The failing test would check to see if ``extra_field`` was in the ``requirements`` key's value. Since it isn't, C2110 would be thrown. Was the change in checks.py meant to check for something else?

**Comment by msarahan** [comment]
The change in checks.py was meant to account for things like this:

```
source:
  - url: blah
  - git_url: blah
```

(2 different sources, each of which need to match the keys in the source section)

or

```
outputs:
  - name: steve
    requirements:
      - abc
  - name: bob
    script: install.sh
```

(2 different outputs, each of which need to match the keys in the output section)

**Comment by mandeep** [comment]
So for the first example, the check would look in ``source`` to see if ``url`` and ``git_url``were keys in the ``source`` section?

**Comment by msarahan** [comment]
no, it would look at each list item, each of which is a dict, and match keys in each list item with the stuff from FIELDS

**Comment by mandeep** [comment]
I think we could revert ``C2110`` back to what it was checking for and make a new check for what you're describing. Do you want me to add a commit for this?

**Comment by msarahan** [comment]
sure, go for it

**Comment by mandeep** [comment]
I see what's going on now. In pdb this is the output of self.meta in the failing test:

```
{'package': 
    {'name': 'some_package', 'version': '1.0.0rc3'}, 
    'source': {'path': './'}, 
    'build': {'noarch': 'python', 'noarch_python': False}, 
    'requirements': {'build': [], 'host': [], 'run': []}, 'extra': {'final': True}}
```

The requirements field is missing the ``extra_field`` key that's listed in meta.yaml. Does conda-build's ``render`` filter out invalid keys found in meta.yaml?

**Comment by msarahan** [comment]
yeah, that's part of what I changed on master of conda-build.  Here's the change: https://github.com/conda/conda-build/pull/2436/files#diff-c86934c27c2f25579540ddb447fa45bdR1609

**Comment by mandeep** [comment]
@msarahan thanks for taking the time to review this hefty PR. The coverage shows that some more things need to be tested so I'll get on that.

**Pull request merged**
