### PR TITLE
Add libarchive support.

### PR DESCRIPTION
**Pull request by mingwandroid**

### CODE REVIEW

**Comment by mingwandroid** [comment]
Well I only ever use conda. If you can assist with this I'd appreciate it.

**Comment by mingwandroid** [comment]
We need to fix these 4 failing tests. I run pytest from the conda-build recipe now.

**Comment by mingwandroid** [comment]
Libarchive system libs perhaps?

**Comment by mingwandroid** [comment]
And libarchive-c.

**Comment by mandeep** [comment]
Installing libarchive-c from pip is enough to work on my system, but I don't know why it doesn't work on travis.

**Comment by msarahan** [comment]
superseded by #56 - closing

**Pull request closed without merging**
