### PR TITLE
Fix version number in test_cli_version test

### PR DESCRIPTION
**Pull request by mandeep**
@msarahan the version number in the cli test is hardcoded so I updated it here. Would you rather me remove this test all together so that we don't have to keep changing the value, or is there another versioning method you would prefer to use?

### CODE REVIEW

**Comment by msarahan** [comment]
ah, darn it.  I thought I had caught all that.  Yes, we need to probably just nuke this test.  As for dynamic versioning, I think it's a good idea.  versioneer works well for conda-build, but it did take a tiny bit of hacking, IIRC.  There's also setuptools_scm and a few others.  I'll put one in, unless that's something you'd like to undertake.  I'm not partial to any of them - as long as it works.

**Comment by mandeep** [comment]
setuptools_scm looks good. I'll add it to setup.py and commit the changes to this PR.

**Comment by mandeep** [comment]
@msarahan I discussed this on IRC and it seems like versioneer is still the way to go so I've pushed a commit that includes versioneer.

**Comment by msarahan** [comment]
Thanks @mandeep - this should work fine, but if it doesn't, I'll figure out what bit I hacked for conda-build.

**Pull request merged**
