### PR TITLE
Fix version specification regular expression pattern

### LINKED ISSUE #25: version spec pattern broken?
It seems like the [ver_spec_pat](https://github.com/conda/conda-verify/blob/master/conda_verify/checks.py#L343) is broken.

According to the docs, `>=1.2` or `=1.2.2` or `>=2,<3` are valid version specs, but the regex fails to match them.

### LINKED ISSUE #33: Conda Verify marks valid spec containing '|' as invalid
```
C1114 Found invalid dependency "pyqt 4.11.*| 5.6.*" in info/index.json
```

### PR DESCRIPTION
**Pull request by mandeep**
fixes #25 
fixes #33 

This regular expression matches the specification provided in the package match specifications: https://conda.io/docs/user-guide/tasks/build-packages/package-spec.html#build-version-spec

I'm no regular expression expert, so if there's something that is more efficient please let me know.

### CODE REVIEW

**Comment by msarahan** [comment]
Thanks @mandeep

**Comment by mariusvniekerk** [comment]
Can we have a release for this?  With the recent release of 3.0.1 on conda-forge it fails verification on several recipes.

**Comment by msarahan** [comment]
@mariusvniekerk 3.0.2 is tagged.  It is known to fail tests with conda-build 3, but we think those are OK (conda-build stripping out errors before conda-verify sees them - not ideal, but functional).

**Comment by mariusvniekerk** [comment]
👍 yay

**Pull request merged**
