### PR TITLE
Fix checking license_family

### PR DESCRIPTION
**Pull request by isuruf**

### CODE REVIEW

**Comment by jakirkham** [comment]
Think it's referring to [this test]( https://github.com/conda/conda-verify/blob/3.0.2/tests/functional_tests/test_recipes/invalid_license_family/meta.yaml#L18 ), but that test looks broken IMHO. Expect it should say `license_family`, not `license`.

**Comment by mandeep** [comment]
@jakirkham the test is checking to see if the license is listed here:
https://github.com/conda/conda-verify/blob/bdb3e6bf43174e08244f4323392297a5c87df0a1/conda_verify/constants.py#L1-L2

In the check, license and license_family are interchangeable.

**Comment by isuruf** [comment]
> In the check, license and license_family are interchangeable.

Why?

**Comment by mandeep** [comment]
It's a carryover from anaconda-verify. Can you provide a link to how conda-forge checks licenses?

**Comment by isuruf** [comment]
Following gives an error in conda-verify. conda-forge check is similar to what is done in this PR.

```
 about:
   license: fitsio
   license_file: License.txt
```

**Comment by mandeep** [comment]
That PR doesn't really provide any info. Is the license checked at all?

**Comment by isuruf** [comment]
We can't check `license`. We have various strings like `BSD-3-Clause`, `GPL3 and LGPL3`, etc.

What's standard in conda-forge is `license_family` which we check using `ensure_valid_license_family` function from `conda-build`.

**Comment by msarahan** [comment]
This code is effectively a fallback.  It treats license_family as equivalent to license if license_family isn't explicitly set.  That doesn't seem like insane behavior but it does seem likely to fail often.  I'm ok with this myself, but I need to talk with the team to see what our current expectations around license_family are.  It's been a long time since we talked about that, and it's time for a re-examination.

**Comment by dougalsutherland** [comment]
@msarahan So is the intention that in any nonstandard case, we should always have `license_family: Other` set explicitly? I think the conda-forge default practice was essentially to leave `license_family` undefined in this case.

Another difference that I just hit was that [`conda_build.license_family.allowed_license_families`](https://github.com/conda/conda-build/blob/53aaa0ff24de55d8b44aa9a8a366a549ce0a4636/conda_build/license_family.py#L8-L22) includes `GPL`, whereas `conda_verify.constants.LICENSE_FAMILIES` does not. I think the default practice in conda-forge is to use e.g. `license: GPLv3` and `license_family: GPL`; if `license_family` should include the GPL version too, then sure, whatever, but I don't see why the two should be different.

**Comment by msarahan** [comment]
The last thing I want is to force edits to any number of recipes.  The license_family thing was originally created to facilitate things like trove classifiers for license types.  What we need to do before acting at all on this topic is to understand how this classifiers are currently used.  If the pattern in conda-forge is to leave this blank, the bug is that conda-build and conda-verify don't behave the same way here - conda-build tries to guess somehow and coerce to one of the accepted classifiers, while conda-verify tries to just use the license field.

The discrepancy between allowed_license_families in either place is nuts and should not exist.  It's a bug that there's any divergence, and an artifact of how the tools were created and evolved over time.

**Comment by msarahan** [comment]
I believe this is fixed by https://github.com/conda/conda-verify/pull/47/files#diff-79e0b9d9379fb79ac554034decf9b448L1

closing, but happy to reopen if anyone has a differing opinion.

**Pull request closed without merging**
